export type IconLib =
	| 'apple'
	| 'atom'
	| 'bars'
	| 'chevron-down'
	| 'chevron-left'
	| 'chevron-right'
	| 'chevron-up'
	| 'dumbbell'
	| 'heart-pulse'
	| 'link-new-tab'
	| 'list'
	| 'pencil'
	| 'person-running'
	| 'plus'
	| 'trash';