app:
  dynamodb:
    running-shoes-table-name: the-fit-app-api_running-shoes

quarkus:
  devservices:
    enabled: false
  dynamodb:
    aws:
      region: eu-central-1
      credentials:
        type: default
  http:
    cors:
      enabled: true
      origins: /.*/
  package:
    jar:
      enabled: false