org: pedroars99
app: the-fit-app
service: the-fit-app
frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/the-fit-app/dev/mongo-connection-string}

plugins: 
  - serverless-esbuild
  - serverless-offline

package: 
  individually: true

custom: 
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  # Body
  add-body-metric:
    handler: src/modules/body/functions/add-body-metric.handler
    events:
      - httpApi:
          method: 'POST'
          path: '/body/metrics' 
  get-body-metrics:
    handler: src/modules/body/functions/get-body-metrics.handler
    events:
      - httpApi:
          method: 'GET'
          path: '/body/metrics'
  # Meals
  add-meals:
    handler: src/modules/meals/functions/add-meal.handler
    events:
      - httpApi:
          method: 'POST'
          path: '/meals' 
  get-meals:
    handler: src/modules/meals/functions/get-meals.handler
    events:
      - httpApi:
          method: 'GET'
          path: '/meals'
  get-meal-by-id:
    handler: src/modules/meals/functions/get-meal-by-id.handler
    events:
      - httpApi:
          method: 'GET'
          path: '/meals/{id}'