org: pedroars99
app: the-fit-app
service: the-fit-app
frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/the-fit-app/dev/mongo-connection-string}

plugins: 
  - serverless-esbuild
  - serverless-offline

package: 
  individually: true

custom: 
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  add-meal:
    handler: src/modules/meals/functions/add-meal.handler
    events:
      - httpApi:
          method: 'POST'
          path: '/meals'