org: pedroars99
app: the-fit-app
service: the-fit-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1

plugins:
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
