org: pedroars99
app: the-fit-app-api
service: the-fit-app-api
frameworkVersion: '3'

provider:
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/the-fit-app/dev/mongo-connection-string}
  httpApi:
    cors: true
    name: the-fit-app-api
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  stackName: the-fit-app-api
  stage: prod
  
plugins:
  - serverless-esbuild
  - serverless-offline

custom: 
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
