org: pedroars99
app: the-fit-app
service: the-fit-app
frameworkVersion: '3'

provider:
  httpApi:
    cors: true
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/the-fit-app/dev/mongo-connection-string}

plugins: 
  - serverless-esbuild
  - serverless-offline

package: 
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'  

custom: 
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  # Excercises
  add-excercise:
    handler: src/modules/excercises/functions/add-excercise.handler
    events:
      - httpApi:
          method: 'POST'
          path: '/excercises'
  get-excercises:
    handler: src/modules/excercises/functions/get-excercises.handler
    events:
      - httpApi:
          method: 'GET'
          path: '/excercises'
  # Meals
  add-meals:
    handler: src/modules/meals/functions/add-meal.handler
    events:
      - httpApi:
          method: 'POST'
          path: '/meals' 
  get-meals:
    handler: src/modules/meals/functions/get-meals.handler
    events:
      - httpApi:
          method: 'GET'
          path: '/meals'
  get-meal-by-id:
    handler: src/modules/meals/functions/get-meal-by-id.handler
    events:
      - httpApi:
          method: 'GET'
          path: '/meals/{id}'