AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The Fit App API

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs20.x
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShoesTable
      Environment:
        Variables:
          SHOES_TABLE: !Ref ShoesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShoesTable
      Environment:
        Variables:
          SHOES_TABLE: !Ref ShoesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET

  RegisterShoesFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/register-shoes.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShoesTable
      Environment:
        Variables:
          SHOES_TABLE: !Ref ShoesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  ShoesTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
