AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The Fit App API

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors: 
        AllowHeaders: "'*'" 
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
  Function:
    Runtime: nodejs22.x
    MemorySize: 256

Resources:
  GetAllShoesFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/get-all-shoes.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShoesTable
      Environment:
        Variables:
          SHOES_TABLE: !Ref ShoesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /running/shoes
            Method: GET
  
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShoesTable
      Environment:
        Variables:
          SHOES_TABLE: !Ref ShoesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET

  RegisterShoesFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/register-shoes.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShoesTable
      Environment:
        Variables:
          SHOES_TABLE: !Ref ShoesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /running/shoes
            Method: POST

  ShoesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: currentKm
          AttributeType: N
        - AttributeName: gsiPartition
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: CurrentKmIndex
          KeySchema:
            - AttributeName: gsiPartition
              KeyType: HASH
            - AttributeName: currentKm
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: id
          KeyType: HASH
Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
